version: '3.9'
services:
#  pgdb:
#    image: "postgres:14.3"
#    container_name: pgdb
#    env_file:
#      - ./.env
#    ports:
#      - "5432:5432"
#    volumes:
#      - db_data:/var/lib/postgresql/data

  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scraper
    volumes:
      - ./src:/app
    command: python main.py


volumes:
  db_data: